config/routes.rb
Webcomic::Application.routes.draw do
  resources :pages

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_attached_file :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, :notice => 'Page was successfully created.' }
        format.json { render :json => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.json { render :json => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, :notice => 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webcomic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
    body{
	    background:#ccc;
    }
    #magazine{
	    width:1152px;
	    height:752px;
    }
    #magazine .turn-page{
	    width:576px;
	    height:752px;
	    background-color:#ccc;
	    background-size:100% 100%;
    }
  </style>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<% if @page.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= form_for @page, :url => @page, :html => { :multipart => true } do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<div id="magazine">
<% @pages.each do |page| %>
  <div style="background-image:url('<%= page.image.url %>');"></div>
<% end %>
</div>
<script type="text/javascript">
	
	$('#magazine').bind('turned', function(e, page) {

		console.log('Current view: ', $('#magazine').turn('view'));

	})

	$('#magazine').turn({acceleration: true, shadows: true});


</script>
<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= form_for @page, :url => pages_path, :html => { :multipart => true } do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <%= image_tag(@page.image.url) %>
</p>

<p>
  <b>Description:</b>
  <%= @page.description %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>